[package]
name = "docked"
version = "0.0.24"
authors = ["Marc Esquerra <esquerra@bryghts.com>"]
edition = "2018"
description = "Thin wrapper around docker to lunch apps locally in a container"
license = "MIT"
homepage = "https://www.github.com/marcesquerra/docked"
repository = "https://www.github.com/marcesquerra/docked"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
